### ISSUE TITLE
Cannot connect after restarting the container

### ISSUE THREAD

**Issue by faltenberg** [DesktopContainers/base-debian#3]
I started the container as described in the Readme with
```sh
docker run -d --name debian-base-system -p 5901:5901 -p 80:80 -p 443:443 desktopcontainers/base-debian
```
Then, I could connect with a VNC viewer to *localhost:1* and the desktop was visible and usable.

After restarting the container (`docker container stop debian-base-system && docker container start debian-base-system`) I could no longer connect to the desktop although the container was running (`docker container ls` lists debian-base-system).

**Comment by MarvAmBass** [comment]
Hi faltenberg,

thanks for your issue - I also noticed some problems with my desktopcontainers.
It seems that some upgrade broke some functionality.

I've already some fixes, but there not yet pushed - I'll try to fix it and push it within the next few days.

kind regards

Marvin

**Comment by gregewing** [comment]
I had a similar issue. I proposed a fix in my suggested upgrades to Debian 10.

Thanks and Regards
Greg Ewing
________________________________

**Comment by MarvAmBass** [comment]
Hi there,

my new approach is no longer use tigervnc and use x11vnc and openbox etc.

but I'm afraid it will no longer be compatible with what users expect.

anyways - I just merged @gregewing s pullrequest and altered it to my taste - should work now with debian:10 under the hood.
Big Thanks to @gregewing!

Hope it works now and you're fine

**Comment by faltenberg** [comment]
Hey there,
the issue is solved now :)

Thanks to you.
