### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by LisBerndt** [DesktopContainers/base-debian#4]
Hello! 
When running `docker build .` I get:

> [+] Building 1.3s (14/26)
>  => [internal] load build definition from Dockerfile                                                               0.0s
>  => => transferring dockerfile: 32B                                                                                0.0s
>  => [internal] load .dockerignore                                                                                  0.0s
>  => => transferring context: 34B                                                                                   0.0s
>  => [internal] load metadata for docker.io/library/ubuntu:20.04                                                    0.7s
>  => CANCELED https://github.com/krallin/tini/releases/download/v0.18.0/tini                                        0.5s
>  => [builder 1/8] FROM docker.io/library/ubuntu:20.04@sha256:703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8  0.0s
>  => [internal] load build context                                                                                  0.1s
>  => => transferring context: 4.79kB                                                                                0.1s
>  => CACHED [builder 2/8] RUN sed -i 's#http://archive.ubuntu.com/ubuntu/#mirror://mirrors.ubuntu.com/mirrors.txt#  0.0s
>  => CANCELED [system  3/11] RUN apt update     && apt install -y --no-install-recommends software-properties-comm  0.5s
>  => CACHED [builder 3/8] RUN apt-get update     && apt-get install -y --no-install-recommends curl ca-certificate  0.0s
>  => CACHED [builder 4/8] RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -     && apt-get install -y no  0.0s
>  => CACHED [builder 5/8] RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -     && echo "deb h  0.0s
>  => CACHED [builder 6/8] COPY web /src/web                                                                         0.0s
>  => CACHED [builder 7/8] RUN cd /src/web     && yarn     && yarn build                                             0.0s
>  => ERROR [builder 8/8] RUN sed -i 's#app/locale/#novnc/app/locale/#' /src/web/dist/static/novnc/app/ui.js         0.4s
> 
>   [builder 8/8] RUN sed -i 's#app/locale/#novnc/app/locale/#' /src/web/dist/static/novnc/app/ui.js:
> #22 0.330 sed: can't read /src/web/dist/static/novnc/app/ui.js: No such file or directory
> 
> executor failed running [/bin/sh -c sed -i 's#app/locale/#novnc/app/locale/#' /src/web/dist/static/novnc/app/ui.js]: exit code: 2
>

**Comment by MarvAmBass** [comment]
Hi there, this doesn't look like my docker file - you're trying to build some ubuntu stuff with yarn etc.
I don't even have stuff like that included in my repo.

What are you trying to do? Maybe remove that repo and do a fresh `git clone` on it

**Comment by LisBerndt** [comment]
Well, I have to see.

Meanwhile I pulled the image from docker and ran it on port 5900.
My VNC only shows a black screen. Scrolling mouse results in displaying "Desktop 1, ...2, ...3,...4" What can that be?

**Comment by MarvAmBass** [comment]
perfect then it works, take a look on how to work with the Openbox Window Manager (right mouseclick gives you a menu for example)

have fun using my container! I'll close this issue
